name: dart_macrolyzer_lsp_protocol
description: A starting point for Dart libraries or applications.
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.9.0-333.2.beta

dependencies:
  async: ^2.13.0
  json_rpc_2: ^4.0.0
  meta: ^1.17.0
  stream_channel: ^2.1.4
dev_dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  dart_style: ^3.1.1
  http: ^1.4.0
  path: ^1.9.1
  pub_semver: ^2.2.0
  very_good_analysis: ^9.0.0

